/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStudyBuddyRouteImport } from './routes/ai-study-buddy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareerRouteImport } from './routes/career'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DbTestRouteImport } from './routes/db-test'
import { Route as DrizzleTestRouteImport } from './routes/drizzle-test'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as StudyRouteImport } from './routes/study'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudyBuddyRoute = AiStudyBuddyRouteImport.update({
  id: '/ai-study-buddy',
  path: '/ai-study-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DbTestRoute = DbTestRouteImport.update({
  id: '/db-test',
  path: '/db-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DrizzleTestRoute = DrizzleTestRouteImport.update({
  id: '/drizzle-test',
  path: '/drizzle-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-study-buddy': typeof AiStudyBuddyRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/db-test': typeof DbTestRoute
  '/drizzle-test': typeof DrizzleTestRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-study-buddy': typeof AiStudyBuddyRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/db-test': typeof DbTestRoute
  '/drizzle-test': typeof DrizzleTestRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-study-buddy': typeof AiStudyBuddyRoute
  '/auth': typeof AuthRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/db-test': typeof DbTestRoute
  '/drizzle-test': typeof DrizzleTestRoute
  '/mentorship': typeof MentorshipRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/study': typeof StudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-study-buddy'
    | '/auth'
    | '/career'
    | '/dashboard'
    | '/db-test'
    | '/drizzle-test'
    | '/mentorship'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-study-buddy'
    | '/auth'
    | '/career'
    | '/dashboard'
    | '/db-test'
    | '/drizzle-test'
    | '/mentorship'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/ai-study-buddy'
    | '/auth'
    | '/career'
    | '/dashboard'
    | '/db-test'
    | '/drizzle-test'
    | '/mentorship'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudyBuddyRoute: typeof AiStudyBuddyRoute
  AuthRoute: typeof AuthRoute
  CareerRoute: typeof CareerRoute
  DashboardRoute: typeof DashboardRoute
  DbTestRoute: typeof DbTestRoute
  DrizzleTestRoute: typeof DrizzleTestRoute
  MentorshipRoute: typeof MentorshipRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResourcesRoute: typeof ResourcesRoute
  StudyRoute: typeof StudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-study-buddy': {
      id: '/ai-study-buddy'
      path: '/ai-study-buddy'
      fullPath: '/ai-study-buddy'
      preLoaderRoute: typeof AiStudyBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-test': {
      id: '/db-test'
      path: '/db-test'
      fullPath: '/db-test'
      preLoaderRoute: typeof DbTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drizzle-test': {
      id: '/drizzle-test'
      path: '/drizzle-test'
      fullPath: '/drizzle-test'
      preLoaderRoute: typeof DrizzleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudyBuddyRoute: AiStudyBuddyRoute,
  AuthRoute: AuthRoute,
  CareerRoute: CareerRoute,
  DashboardRoute: DashboardRoute,
  DbTestRoute: DbTestRoute,
  DrizzleTestRoute: DrizzleTestRoute,
  MentorshipRoute: MentorshipRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResourcesRoute: ResourcesRoute,
  StudyRoute: StudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
